### ISSUE TITLE
2022.3.X Breaks dropdown

### ISSUE THREAD

**Issue by regevbr** [ljmerza/light-entity-card#84]
You are using paper-menu-button and paper-listbox with the assumption Home Assistant will load these elements.

In 2022.3 these elements are no longer part of Home Assistant, so this will no longer work.

see https://github.com/kalkih/mini-media-player/issues/606 for reference

![image](https://user-images.githubusercontent.com/5775519/155720841-cbe3c5bd-01a3-443f-8327-1b9eb5512a92.png)

**Comment by SmarterHomeLife** [comment]
Same for me, breaks the dropdown completely so options aren't clickable even when shown.

**Comment by Psytoshgen** [comment]
+1 got this issue about week...

**Comment by antro31** [comment]
+1, same for me

**Comment by niclasniedermaier** [comment]
+1

**Comment by compujunk** [comment]
+1

**Comment by ljmerza** [comment]
looks like id have to do a bit of work here to get this working again. Unfortunely, I dont have the time right now to look into this but will look into any PRs anyone is able to add.

**Comment by regevbr** [comment]
> looks like id have to do a bit of work here to get this working again. Unfortunely, I dont have the time right now to look into this but will look into any PRs anyone is able to add.

Done, To use the fix until it is released, follow the steps I made [here](https://gist.github.com/regevbr/df6e51fd3b1d4e70cbffb296b3d49f9d)

**Comment by regevbr** [comment]
Css is out of the scope of my expertise, I will leave it to the maintainer...

**Comment by dashdrum** [comment]
> > looks like id have to do a bit of work here to get this working again. Unfortunely, I dont have the time right now to look into this but will look into any PRs anyone is able to add.
> 
> Done, To use the fix until it is released, follow the steps I made [here](https://gist.github.com/regevbr/df6e51fd3b1d4e70cbffb296b3d49f9d)

FYI, this fix works for me when using Chrome, but not in Firefox, where the effects dropdown looks the same as the unfixed example back at the top of the thread.

Thanks for looking into this!

**Comment by jsiemek** [comment]
For me works OK also in Firefox. Did you clean FF cache?

**Comment by regevbr** [comment]
@dashdrum I just tried it on my Firefox and it works well. Indeed when you open the menu it can cause an "expansion" of the card (also in Chrome) which I mentioned [in the PR](https://github.com/ljmerza/light-entity-card/pull/85) and I don't know how to fix, and I will leave that for the maintiner. But unlike the issue, the buttons are still useable and the menu is not stuck in open state. Can you please verify for me that this is indeed the behaviour you are experiencing?

**Comment by ljmerza** [comment]
should be fixed in v5.0.0

**Comment by bistek22** [comment]
It still does not work
HA v2022.3.5
Light v5.0.0

Cache clear Firefox and Android 

Firefox:

![Zrzut ekranu 2022-03-16 225801](https://user-images.githubusercontent.com/72106904/158698244-ff2c770c-c3b6-463e-ad14-a5d0c192705f.png)



Apps HA Android:

![Screenshot_20220316-225348_Home Assistant](https://user-images.githubusercontent.com/72106904/158698877-8f2b0ff1-ed7a-412b-bfd7-be064da00ac5.jpg)

**Comment by regevbr** [comment]
The first pictures are not related to this issue.
About the app it seems that it was not refreshed yet as it seems like the old ui before the update

**Comment by dashdrum** [comment]
> @dashdrum I just tried it on my Firefox and it works well. Indeed when you open the menu it can cause an "expansion" of the card (also in Chrome) which I mentioned [in the PR](https://github.com/ljmerza/light-entity-card/pull/85) and I don't know how to fix, and I will leave that for the maintiner. But unlike the issue, the buttons are still useable and the menu is not stuck in open state. Can you please verify for me that this is indeed the behaviour you are experiencing?

I can confirm that it does indeed work in Firefox.  Sorry for the confusion.
